from app import db

class Player(db.Model):
        id = db.Column(db.Integer, primary_key=True)
        player_name = db.Column(db.String(100), index=True)
        position = db.Column(db.String(100))
        first_nba_season = db.Column(db.SmallInteger, nullable=True)
        field_goal_made = db.Column(db.Float(31), nullable=True)
        field_goal_attempted = db.Column(db.Float(31), nullable=True)
        field_goal_pct = db.Column(db.Float(21), nullable=True)
        three_pt_made = db.Column(db.Float(31), nullable=True)
        three_pt_attempted = db.Column(db.Float(31), nullable=True)
        three_pt_pct = db.Column(db.Float(21), nullable=True)
        free_throw_made = db.Column(db.Float(31), nullable=True)
        free_throw_attempted = db.Column(db.Float(31), nullable=True)
        free_throw_pct = db.Column(db.Float(21), nullable=True)
        true_stg_pct = db.Column(db.Float(21), nullable=True)
        points = db.Column(db.Float(21), nullable=True)
        off_reb = db.Column(db.Float(21), nullable=True)
        def_reb = db.Column(db.Float(21), nullable=True)
        tot_reb = db.Column(db.Float(21), nullable=True)
        assists = db.Column(db.Float(21), nullable=True)
        steals = db.Column(db.Float(21), nullable=True)
        blocks = db.Column(db.Float(21), nullable=True)
        turnovers = db.Column(db.Float(21), nullable=True)
