"""player table

Revision ID: 1578d14f988a
Revises: 
Create Date: 2019-09-08 23:24:59.425545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1578d14f988a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=20), nullable=True),
    sa.Column('first_nba_season', sa.SmallInteger(), nullable=True),
    sa.Column('field_goal_made', sa.Float(precision=31), nullable=True),
    sa.Column('field_goal_attempted', sa.Float(precision=31), nullable=True),
    sa.Column('field_goal_pct', sa.Float(precision=21), nullable=True),
    sa.Column('three_pt_made', sa.Float(precision=31), nullable=True),
    sa.Column('three_pt_attempted', sa.Float(precision=31), nullable=True),
    sa.Column('three_pt_pct', sa.Float(precision=21), nullable=True),
    sa.Column('free_throw_made', sa.Float(precision=31), nullable=True),
    sa.Column('free_throw_attempted', sa.Float(precision=31), nullable=True),
    sa.Column('free_throw_pct', sa.Float(precision=21), nullable=True),
    sa.Column('true_stg_pct', sa.Float(precision=21), nullable=True),
    sa.Column('points', sa.Float(precision=21), nullable=True),
    sa.Column('off_reb', sa.Float(precision=21), nullable=True),
    sa.Column('def_reb', sa.Float(precision=21), nullable=True),
    sa.Column('tot_reb', sa.Float(precision=21), nullable=True),
    sa.Column('assists', sa.Float(precision=21), nullable=True),
    sa.Column('steals', sa.Float(precision=21), nullable=True),
    sa.Column('blocks', sa.Float(precision=21), nullable=True),
    sa.Column('turnovers', sa.Float(precision=21), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_player_name'), 'player', ['player_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_player_name'), table_name='player')
    op.drop_table('player')
    # ### end Alembic commands ###
